// ── helpers ──────────────────────────────────────────────────────────────────

function topoSort(nodes, edges) {
  const inDeg = Object.fromEntries(nodes.map(n => [n.id, 0]));
  const adj   = Object.fromEntries(nodes.map(n => [n.id, []]));
  for (const e of edges) {
    if (inDeg[e.to]   !== undefined) inDeg[e.to]++;
    if (adj[e.from])                 adj[e.from].push(e.to);
  }
  const queue  = nodes.map(n => n.id).filter(id => inDeg[id] === 0);
  const sorted = [];
  while (queue.length) {
    const curr = queue.shift();
    sorted.push(curr);
    for (const nxt of adj[curr] || []) {
      if (--inDeg[nxt] === 0) queue.push(nxt);
    }
  }
  const seen = new Set(sorted);
  for (const n of nodes) if (!seen.has(n.id)) sorted.push(n.id);
  return sorted.map(id => nodes.find(n => n.id === id)).filter(Boolean);
}

function toCamelBase(name) {
  const words = (name || 'Node')
    .replace(/[^a-zA-Z0-9 _-]/g, '')
    .split(/[\s_-]+/)
    .filter(Boolean);
  if (!words.length) return 'node';
  return words[0].toLowerCase() + words.slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function escapeTemplateLiteral(str) {
  return (str || '').replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

// ── main export ───────────────────────────────────────────────────────────────

export function exportOpenMultiAgent(graph) {
  const sorted = topoSort(graph.nodes, graph.edges);

  // Build unique variable names for each node: e.g. "researcherTask"
  const varNames  = {};
  const usedNames = {};
  for (const node of sorted) {
    let base = toCamelBase(node.name) + 'Task';
    if (usedNames[base]) {
      let i = 2;
      while (usedNames[`${base}${i}`]) i++;
      base = `${base}${i}`;
    }
    usedNames[base] = true;
    varNames[node.id] = base;
  }

  // Build dependsOn variable lists per node (upstream variable references)
  const dependsOnMap = {};
  for (const node of sorted) {
    dependsOnMap[node.id] = graph.edges
      .filter(e => e.to === node.id)
      .map(e => varNames[e.from])
      .filter(Boolean);
  }

  const lines = [];
  lines.push('// Generated by Orchestration Canvas');
  lines.push('// Install: npm install open-multi-agent @anthropic-ai/sdk');
  lines.push('');
  lines.push("import { OpenMultiAgent } from 'open-multi-agent';");
  lines.push('');
  lines.push('const agent = new OpenMultiAgent({');
  lines.push("  defaultModel: 'claude-sonnet-4-6',");
  lines.push('});');
  lines.push('');

  for (const node of sorted) {
    const varName  = varNames[node.id];
    const deps     = dependsOnMap[node.id];
    const sysPrompt = escapeTemplateLiteral(node.systemPrompt);
    const model    = node.llmModel || 'claude-sonnet-4-6';
    const provider = node.llmProvider || 'claude-api';
    const depStr   = deps.length ? `[${deps.join(', ')}]` : '[]';

    lines.push(`const ${varName} = agent.task({`);
    lines.push(`  id: ${JSON.stringify(node.id)},`);
    lines.push(`  name: ${JSON.stringify(node.name)},`);
    lines.push(`  type: ${JSON.stringify(node.type || 'agent')},`);
    lines.push(`  model: ${JSON.stringify(model)},`);

    if (provider && provider !== 'claude-api') {
      const providerStr = provider === 'openai' ? 'openai' : 'anthropic';
      lines.push(`  provider: ${JSON.stringify(providerStr)},`);
    }

    if (sysPrompt) {
      lines.push(`  systemPrompt: \`${sysPrompt}\`,`);
    }

    lines.push(`  dependsOn: ${depStr},`);

    // Type-specific extras
    if (node.type === 'tool') {
      lines.push('  handler: async (input) => {');
      if (node.toolType === 'bash' && node.toolBashCmd) {
        lines.push(`    // bash: ${node.toolBashCmd}`);
      } else if (node.toolType === 'file_read' && node.toolFilePath) {
        lines.push(`    // file_read: ${node.toolFilePath}`);
      } else if (node.toolType === 'file_write' && node.toolFilePath) {
        lines.push(`    // file_write: ${node.toolFilePath}`);
      } else if (node.toolType === 'grep' && node.toolFilePath) {
        lines.push(`    // grep: ${node.toolGrepPattern} in ${node.toolFilePath}`);
      } else if (node.toolRestUrl || node.endpoint) {
        lines.push(`    // REST: ${node.toolRestUrl || node.endpoint}`);
      }
      lines.push(`    // TODO: implement ${node.name}`);
      lines.push('    return input;');
      lines.push('  },');
    } else if (node.type === 'memory') {
      lines.push('  store: {},');
    } else if (node.type === 'router') {
      if (node.routerMode) lines.push(`  routerMode: ${JSON.stringify(node.routerMode)},`);
      if (node.routerDefault) lines.push(`  routerDefault: ${JSON.stringify(node.routerDefault)},`);
    } else if (node.type === 'evaluator') {
      if (node.evaluatorCriteria) lines.push(`  criteria: ${JSON.stringify(node.evaluatorCriteria)},`);
      if (node.evaluatorScoring)  lines.push(`  scoring: ${JSON.stringify(node.evaluatorScoring)},`);
    }

    // Shared memory annotations as comments
    if (node.sharedMemoryReads?.length)  lines.push(`  // reads from shared memory: ${node.sharedMemoryReads.join(', ')}`);
    if (node.sharedMemoryWrites?.length) lines.push(`  // writes to shared memory: ${node.sharedMemoryWrites.join(', ')}`);

    lines.push('});');
    lines.push('');
  }

  lines.push('// Run the pipeline');
  lines.push('agent.run({');
  lines.push("  initialPrompt: '', // TODO: set your initial prompt here");
  lines.push('}).then(result => {');
  lines.push("  console.log('Pipeline complete:', result);");
  lines.push('}).catch(err => {');
  lines.push("  console.error('Pipeline error:', err);");
  lines.push('});');
  lines.push('');

  return lines.join('\n');
}
